/*
Given a string of lowecase letters (ascii[a-z])
determine the index of a character that can be removed to make the string a palindrome.

If word is already a palindrome || no solution = return -1
Else, return the index of a character to remove.


*/

let string1 = 'bcbc'  // 3
let string2 = 'aaab'  // 3
let string3 = 'baa'   // 0
let string4 = 'aaaa'   // -1 (palindrome)
let string5 = 'hgygsvlfcwnswtuhmyaljkqlqjjqlqkjlaymhutwsnwcwflvsgygh' // 44
let string6 = 'aprrmdeykhorwsalkysinbvylgcgiaokrifgolfytvsqqufctxkjbijnonvapmkivrokewlasfskcxowyyiakrpyilyxbmgygxjkuwmpegcheqgdsogdjverkgpnuymbyxovublchqjojptegahpyojlucypdnqclfxijlkqevhoncsuedmftwsoytgchygsheeqrojwlrnbvivanjihibvjvelderylxderrnqffehdnfebqmlypjilovrspqgpvkipabvigflvkryegkdwuoklmcedumuqyfhyhfjpkvnwnmbuahtwxeikjopednxcsfdcmnrwlfvbuaxwhrthyeriskovxoasvdvisnhgveisggppblwapqkkbbiyqismnqvhgdnejxwrfohgaeirvuewvmyoutcjkassfixphuhmmruovfhtaltxysnvophbpatwjrmspwhcqcqmjahjobhpvulmmtnevjchcqarphvglmvwpfgeiqtenfsdbghxplhtdknstjciyxfofmsnfmtutmxvugvmrfhwpwsmjuukuabaovpvijrevpcqxadqgmpxmikvfhgcijcyfrvpdntydyrcyxuhmkiyvuwbdfenoimtdkjgxgiefaigxdonpwmltmpwrvkheadhkpqlvypbyxhadxnswchroyojucsyevjonaajyrmarwcuwpquuamlyduvhpulogdcidojxbmpaonxhescehpfknbudxgthjwpplcnoofpdsnmyiofphkcunwaoguvptnhfpwtgdlmxyyxjqdyxqeuedwujrqalhjswhpgmbskdrimiooifsdlvdhiuakjhtehbtnnxgbbajpjagtfyatxdbiabsjlmosqkggiohjotcatiuckuvkaysaclknabgqloxudfgsbisvtpxemtomuhnwualubtmojmjmtqhvbbruqrygnpsiwghriupjpcyboknkdvgfyacrrexhtrptaxnjudukhvlxhcjkapryswqkbrswlkqlkfwgkussqhqajanjsfklcdxfusdgetuqbtymoshicxilbvwtcjhgmfokyrsfnpvrkxgbsnjunsioofksqrcdxqpwijexyaplavnsjwnxpvohdaattcatspqdbwcbxroxqctcahargryjtcenegiavbdxyhbycrysusuwdxqjrqslsybyflyenfeomhpoyqjvkfspfkywdtixtlybxyhlencsuriwktsuymmgyldegnccabfxcnlidpcyjmvtgorideocsuiyimdkqkksxxcengdysbtyrnjvryaktjlevormaciabmeqsjqnkmofaybrxdftoqanirckwkmxytqrfjhsvwxvvbqvevrtorhykllhwbhvuaqckaugwsfutxqbvkumdemppayobinxigbugvegpjblhumffjrkpeaifbyijmhusipcetivdlkmgyrolkybqclxdlhnaqityaxfugearonbnhrbtsfnuqnbewofnybmyyuvhywbnmcdtvfqpkekdrnipcnfdosfppdwoaxemdhjyoaqbgcfarprudxatshjiliwngbbjkmlaocdugkuyanvflxyeikotsljcomnyyybnefkkpglqvhxjiapqkemgpvkejxfkahygojsgrfypoxywxopkscqkydqkewuegvkwiddakdsabryyjpjcrdpsggdkfbqnwdkhjoktrdvuuxtgnfjhibbrjgepjvfjbqqmhbjygftedpksuvbgwexhmcywaggewyqebafjibnlsyhoukuuouebydaaligjiwplxxugbjtukdlfngcedgicliexrkjcibniykqdtmxgqjogrqluxtyjeejvosxwunhvyxbunycgkqmejxbhtbtyfdutyvtvldrkcvirukxidkmmlowfpseuxcqwamslqnyujhmgtkowueliukokduhcwabynulekkyttncnxrmuxaeslufqpounowmetaiemjxgyavwtiutlbmyvtrlinbxkoeeqnkeyimbkjahtudfvsgtmygvmhvyxafpppvraismrsvoqavosdjferdqbbracwrtonloxgdscahscfjuiucomihojyqnxiioxtdvbjodjxxnehkodmerwlihlyuljdbhaggdpwgbvgqapbosounnhvwuvsgfxjpasxdiujmqrdqifidvdqlmnjhleqsccidugggcssumxoufyydcrprfbbsfrmjuumrevxiqqddrtbyscfxtwpaxqsdlhmifcajaytqryvjtwlmyqmvncxnvsshbfpgjprjqlcjmbugagvcyixonvcjouqpdivmapyrbdboevwhfujeghvtfxftvxmygkngboxesbuyasghprnvbjrgiwdeurfbcskfkkmdoheocnvsfjohthpegskckpfpkpwubjaprfgtscoanejjnantuxxipexdtwxwhyoygwubykbpqnygnncknbsghsjbqhbxiryqptrqgvgyjgfyvkjlldrsvdvolymvrlnhifaqdhqopxnniayvftqdwpskohhiturecswianwronfwpetuxkaxasirbpawmsdrncapqyhfmmeesxyrlcpnuxhxqkwdfcwsfwixypfncjsuktoxvgnthvtagtdnvdgdaodbgipkuihfewfbfsuoqooykumjxumalqcrbrcvckdgjkjqgggwvuyipnrnjfouxqnbkraoedwnqjfwpnvniuwblooutfptxfvkxvycbystiaqanpoxklyvaqswvlsuqqfqmhvqiomsqesethegsefvuxsqlnndfvvrdrknixgyeyfahmicqnxnosgchufmqcgvvtjhtpgxqoaadidtydhpwprgkasdebbaumhoeqovhqvkaygbdpscfmisobxscavamfqrxgnhwlrynacqpwuxkdqygoukqqkevcxwknejywjmynfrlapxfiwlytwqkjwjnugxkkkjjtyjjeduhsumdubeoxuajtjaqrxbcinoeoaqsdncxjpdeshsqfucyecsxdvdnjruxrltwbxuknxoifkymfemmihkldncnhwnbkjxliuyxunhdaipgmeuxlhjpxlffksjwfhjnfilaxufyevhsaeqmldcjqjrccbyhikwpujstgxuktegwiwjvangrwxvbywljiicftuybsvnnctkkrvhtlpnknjlohyaricwewyfqwvgapsmjqveclrobecpncsfmuequdylbutdkmpwfmdhxuxabarocmvqibifghqjemoqbfngrqprontrnohsbfjlitqrdjbhvsywxodrgsjwieowsxrvedimabedlinjbmjbdmsjiciqixpdvjaapkppltuyeijhusiyhbkretlmtbqrnssddkuqgpqlycsvwcugdiyjekwxnprbimgnwbeerwpsykoxomfsugcbsbbgsskbgsqduvjoubhumvubkcvhiyibcjkvfuylnqqkobbjckgqjcsteqcppkquwbsexrpokibyldlonrhyvctbtvsjijghnylntdcemegxjroyjwygysjsqcfbnnjdnurjbtnnatnjnfjxcigddpyttguhtgljcfsfyjscfintnytrjavmrwgndeuykijonetpporxxhrnhngqpeejbmwestfedousvringclgkfursbikhotieqowltdqlbjhsswbujihofyiikupbpafiofviimvjyferdgomqwbxxlgkhxmyxtjoygwkutvtbbnejdqccuacginpicqixbwajtkepiytjoxurryvmyyujoltsecqfyqovdvlmwfxlgtgxsckudfgrsbkxdefduwyysmlrujddflbbonvruemofwolbvqysrxnglhdwlgdwjenwcisiujoracvvsupmufsinwfbfiapoomswhcrsslswjppehcbmwjctpdaagrruektoonhjbbglsxractoafrvwwxxdppawcvltludnxkyqksqnognualrykrdcjfyocminildgxexjxqymyohyacyktepgloupcdemqjsrosdmkcbjqllqnmejstrekmumrbblkudyninakpkddxvskccdxuhjjexcfapqwurmdinpaaudxqvkvaptwyfhegljibcfxutbdhsfjnijegtaglwelenpkybsceaaywdegvlqjtcpaysikpmvtanhbpcftfhuckbigmbrgeiidbqnsgmmiavkpyrjeaegkfqtrulayvkewcrpkgfshbdwaxjgxnokviendsqcobgofaepjljqpoppmyyknnvlvcbburdmvlbbohtxvdolredhgcrtsphquispbxeykfabptylypwtvabcfuxxnfoiojxrifqsksvcpunomkkinlnsjlswtjfktfcckuwvpsafpowcbhmqvajfoeciohskmwmxrlvhgvpxmmcovofrrrwgvyqmglwvilvcytlhrbffpjvmbdgswebvdtimfikntgpvcddtfjywuwlvbsoxwrtclfqqnbghjxflcjgjuhgpfsmglbgkvbmhggythfdtgjfiunrpvafbsrjgvpsrqiyyoauxibromawhnqwjqekmwtuumqodyndpqanybipniouvhtixyumxpkscbhhcwmrpnhqqpgfawcyewhdxcrvtcqxdxifwuynkhecynjcknbpmkukmmijpyhuyrdwpemalqeneprreshqfceromdgmnelfhkunwxaqcpwuhobcxthaxbrlfxauenanyxcxveqatoudfvhesoeqrveywgtbuwpvurvsvnurcqwjoenhuubmshopoktjhlfefdydquuunrfexsospphjwvblhuwqievniwqyrnufhakfuyalqiupexenvbfegduqalpucmclmmrknrxgcswhsbwoeetkjobmcthggjsvykioegvhyuqtxpjcudpetsqxmxfvkxrjkcaqivajsqdqhmterjileakrarpmrjxelyutwvdqoghxtdclonatpmnpedfxmdcxcyrawusmdcmwirlwflsuxgmelrcxxgxafpcdmwrqaepixbhdobaojnsvhwvfduilmmoakgskmiulmcqbfrqphlnoljwqefcrtqteymqowlajqqlvkenrrbjdngutnwnhqjorvfgttgdkaqimuyfncqspynmmnavgkkxisfemnkypbhdygkojbhbcxnonqmtdarnsyshndgfgpihyuvkxelaecqruelagfnyhiiwnocwgnefibphhejnibffhsfnxuofgwcvnhstuxcdbrmkxyxiafnjxuwxqngymkuarqvoqxursheqgecilprjlqjeepfqdaswqpmhnhbiqhcaneiytdihtunyksrpvlnobayqhcaakcaaglacokmifajsveirpxgsxhjhkliwpkwxvwbkkpvpphkllvfbtovuvicgtmdkxbktalhkbddtkphylncgeybahfjdsopsrbmsovfsykombvlolpupoxsxgcebsttlwiemflhgwvsatgogwmxnmsmswqtqmpckyiygvimseiuaqkgnyhelcqhajdsxtwiufjbdrnyxxtypghffqjrtcyvlcqkvnusuhtxbkwcitbaakggcpxxswvgboqacosyxpyyawbkqenqptwtjwtevrlxgeaiusjskiumhvaxdnruhqosokamclmirmsnicismdgucgsftmadgqvwbvjfjwpejitrmcnyittkaprverykkwhnvrsfqilcsfwfkkgsedfguwcyqbmbxtotnhcernjkvgpgqxbwbgdvfhxvkkyignfuwjbqykbussdlqgkumpqtwqrhbqsigxffjgvityeorjblqlgfcyabqrjrlecrehanqvvmvabpmebdshiuhkxadhrqnwkrekfwjcjhenwqrbtkkfhtpgtupolelwvrjepsgbcmocejdatpfekvmeqcsfieehwnlojrplgfpkounkluovqbakgvrqavxyjjnsdghklywcukmggecyhelpadhdyfelpuesbnfondqipfqxjuxtyjjcpqhownaoihjlwpcmuswkbnjkijekuqmkhvcejesundglujxpexcfllswwyhspvdathedmaxafhnasopymthxiaufbextcetvlxaaaabfjqfefwertlscnphquikwoevcfxdfxgnkwuoduuwogpqvganbkxayfvckthrunfhmdxrxtpmcffylfoosorrtpvgkdyhsgqgloajipxnvdmjldbersxoiuuuxvetfucqkcbusbiqfwcsadyuvwjhtgcudjoieqbqsemlguenshgskhpjgysbguvlgkvldwcvcokkmqxfxgalpqwvrpwxmultfhfkfjjjbvvnmtuncubrnxngnngaisvqcdbhnmsqioexkylmvmgkmwsakycutylwcpgrcainqolcpyqmnayawrajseendqmiiscmunaoensumjhajgaiacrshwgmpuwxocmlpnctbuqqfxqqgtagxtchqkuigtiwvvinllkmibfncwhisjrqdtywgvhmrqjomuexiomqqshurofmayffugeccmowdynrvrpejeuaycwsscfucnbwtfyyrovupjoldgpmlmomplgkongqbjnxopwjeugvevhhcyupljddvlomywddgsbwkagqupmbltkpsfghrjkpuycvxhbeceengmebctepppglwmsqxdgufksdtukybomibslgoqvfgcqfqjwoofjtqdamaklbbajctxkkohpwlgcdryrjfedxjdkjpwmqwyvswgelnvkafmdwowivdmtmrgvkdlbdkwvjgcwtyhvetbdkbmgebcrujpfmbjrngqwostjtbhaxjgkksrqvviqfyyucimqqdpgwkrsnytnkaywusosoyluxkpducvoglufvoamptadvycsrqlhsxesktvixrwgetlckmoairffqialbmutmynysjhsegaialmkaenjvsqobqadfwytvmtqydkdkknkxcxyglkegdtkvvpetoxperjdvtiigvseasfhgplnufarepxxgvpkqbpmuxubvpiwlngrgrhbahugysegpvsgxjuujrygjhfuulpbfyfhjanivtqlqmtqvqlhkkpvtutrijsqkaatbofwkxkdkgtiyiqjugfpeyhokchvdirgywdjvpngvjpwrignonfupokcstxvcqebpjnlybuwkmtfuculschiqtkjnlisemttwhixkdvxrrdmwaapchxsdketxomceiydsjbdoydgtgsqiugkdgfiqmepbqtfcukueoasneyjmtavpgguomfgykxcdtkfpuctjdnajojvjmtbubvkpbsqlqurmfwcdaymfmoodbmmnhpiklscplsdepurvuvywuncjfsnghctoscbgvdvjxaoowikreloabsjgnyovcimwnodlrauqcjfbtrtydkyggkptmepopdldroolqjcuvhwpbqqedrnjddepjvgybtcsksfcfjwdttsumkcqcpchuiyefhegbicmejqjspmmmhkytmryeuiydidkrhrtstiwdbixqunfexfbkyaovincssmlbghvcruhudgnattgtbhechuysiblbpyeyicbcwlyctncpjjjksnobkntuqhxjjfithlyhwxjqlogwarhsfwvrmpmgalplqafxlehldreqinoifxdnwafmrssreidwklwvpfhuyoohcdrhduudwdppvihcsnydyxbqdloeadncgflldhocmeriocmhrnmqlojraxvabkejrpvuymxlrrvitislxfekvqcvoxxskecdwaavnakhsgporkdpqhcmxelpflipqmunpvlfxvmqfeiyploistutxijfutxlisbxqmdpjrgoyqpoceyvavryfdgayenhaogqbjgkepbdgqtjxshxobyteivdmjmmxsgcfomjgqonjiyjdiirljoprmuhwhvwdcyitotahinqqobvylnkwecrryyqhunmaputeqtlykerbhnbudnsiqkcplsygilixieebyralwtoejrcpguayhcqswsbfemgpqkqrdtfcpuicmkruhrtovljsenakagcstvnyrsbjnjldwdxewuvsgflmumywueqoaentyqdnbpsxuqeslaltgaidmkbhotyqaokygpmjhfhdynxmojhujraxcbiqujjuxvwemjntrwwslwfahowshwtlbefxnovllssaegtvgtqrqwtanqvwprjsvqrjfnwsgpsmwpjdjcwayqdpjymysvsommauawpinjumygrkjomkfpcqqppjnkadyaayxpjlbhxcppmygcmnroelgtwuhxagxaivptjtbjvrblshnhuhyysfvqcfqcnocvnuqwotjmlkxhunopvnrovphxuxbipfhdaaaqvlgkwerrsijqwdfuspsppvbfciieklxgyeqvkkpftavsdenytgoldprhacnmplvpponbaegtefmjjcifiaqnpkwsplfhwbwpqnssrymxgbhpdsunsoekbbfqolymoxchlucdvobfrluwgsnbjtnkutckhbyxydgnakqxcudtibtqtjrfdfpabtmiwlhwqpksadrcxuyixsyteqyhyphalwjjksicisukxmnykmhihjdlceubveeibprmiaosuldsbqtnfcxondapiwrecvmdnepvggoburwvlqjquhgiliytisakqnnetgaboqejibfvsqnnbvymgxiqskbjxrnuapxogcyqggnyadobbppjpabikerlvhgxygnhiobowqpwthxwynipnlxbqsmocsncydljrmbqdsoycovcfhrusrvjkibndorerdolsrcvkqvpgtrnbliwdfiqnjgrxavrdmdveiuryqhhmbwqmgnrlviygosgoryueeslmpdoikxvlvmacarnxdoetkllcmigsbtgrwwcjuxwsmwumrknucroofaqtiynmttgssidnjajvaglrryovsdkygdsqcifxenrwyuniwwewdrqwsfumlfntiiknrsnvgftfchpagwyjoqjivewhkkbusokkhyhpgdxjmnjskiecbnmxsjhftjamanajmjysmyebnptabxccooahxkmrtohvchfqsgmfgqitjcvkcymsppaoaoiverriyycrfqyljhhsledqfsjuimjibuehmxsowuiclkqwtaqgetylokhwwshbnnkdldrkaapnkglfgcnnxoynyimycuarimuwqmhqnwhafsfowucwjdkjmakqukifwecpqmjglqjtlqiimmhxrshestwpgguekavdohmaxvvlmevbsealyjrtepjkvgqiipnwwaavxvjndgqvmqjldcfhtqtrylaibphxsjvqiignoxlbovorxvbtmvlnjlvkbgktrjnartnitcljxcdxxhrmddamqyytflqwweaqapyurmgrolpmshyxmamdbnxgcqfywhqwartrfckvqcllkkkymydnndvrteqqlhpncmghqsfhwqtjegjqhmhwrfonjggxpvlrktbcohlmxhvcpfvxtfulkkbwshuiggdqdeurnjemqdqhimfftasfmucfcyoifrakxwdmgjbxmrhxhmdbovicqkjtjxerrecsehfkrgkearehghlxgtcwhlssmxmeepwiyevqkixndcujmijsdlpmxlfmjsqpkqyjuwdifbvifsurcekhqdtqoyfatvpeoqqmntwtwucenywrejywmspbuudqstxkkowykvujqyngykyfwxcjttnqoqjjkhtvxswkotthskotwnytnbejutclkmxvvrtunshcmckhobclobgefmocgsqshooegkbtfiytklcbmendhvhmkxrqrijywbdfnecvpbpcorebxregpnuammsgueftflavrcrhfjktcoucibiaogabsshqwpkfbmduowftgppigklqlvqdcqexloqkedphquchrjeyytjhhuxutqxxhdxutogxuxhntjulvbmuvwfftfanwyogemcxekxyifmcqjqmldkjcpqwuqmrpbbvqdtwnrvvwkbqvtdjynucdlbbdpuurvrkbnhoifnhrqxnmcalrupxjsyojtjdsdnttwlceylvrkleolrgj'
let string7 = 'quyjjdcgsvvsgcdjjyq'
let string8 = 'fyjwtatuieusvfqaeynaaiiaanyeaqfvsueutatwjyf'
/* test case 1
'hgygsvlfwcwnswtuhmyaljkqlqjjqlqkjlaymhutwsnwcflvsgygh' // 8
'fgnfnidynhxebxxxfmxixhsruldhsaobhlcggchboashdlurshxixmfxxxbexhnydinfngf'
'bsyhvwfuesumsehmytqioswvpcbxyolapfywdxeacyuruybhbwxjmrrmjxwbhbyuruycaexdwyfpaloyxbcpwsoiqtymhesmuseufwvhysb'
''
'mmbiefhflbeckaecprwfgmqlydfroxrblulpasumubqhhbvlqpixvvxipqlvbhqbumusaplulbrxorfdylqmgfwrpceakceblfhfeibmm'
'tpqknkmbgasitnwqrqasvolmevkasccsakvemlosaqrqwntisagbmknkqpt'
'lhrxvssvxrhl'
'prcoitfiptvcxrvoalqmfpnqyhrubxspplrftomfehbbhefmotfrlppsxburhyqnpfmqlaorxcvtpiftiocrp'
'kjowoemiduaaxasnqghxbxkiccikxbxhgqnsaxaaudimeowojk'

// test case 3
'qaaiyrpadovfjrmgkildtkseysejdtrpltptujlxxljutptlprtdjesyeskdlikgmrjfvodapryiaaq'
'llhrxcreddwkcronujfkwbdswoowsdbwkfjunorckwdderxrhll'
'qasfhkfcojhntlfkaydtepsfsleipymwsopposwmypielsfspetdykfltnhjocfkhfsaq'
'broifqivnnvifiorb'
'bglgcwnmpobohqefrglsaaaaslgrfeqhobopmnwcglgb'
'bthvmywukfwrkslaiialskwfkuwymvhtb'
'uxxdlselxmwyiguugtpsypfudffswvwyswyyiiyywsywvsffdufpysptguugiywmxlesldxxu'
'rvscdpyljqglgmiktfndsmfnkgmubrruloqptgohsgneocoyyocoengshogtpqolurrbumfvyqxqxynewuebtcuqdwyetyqqisappmunmnldmkttkmdlnmnumppasiqyteywdquctbeuwenyxqxqyvfgknfmsdntkimglgqjlypdcsvr'
'qmdpbsswvmqtyhkobqeijjieqbokhytqmvwssbdmq'
*/
 
function palindromeIndex(s) {
  let result = -1

  for (let i = 0, j = s.length - 1; i < j; i++, j--) {
    if (s[i] !== s[j]) {
      if (s[i] === s[j - 1] && s[j] === s[i + 1]) {
        if (s[i + 1] === s[j - 2]) {
          result = j
        } else if (s[j - 1] === s[i + 2]) {
          result = i
        }  
      } else if (s[i] === s[j - 1]) {
        result = j
      } else if (s[j] === s[i + 1]) {
        result = i
      }  

      break
    }
  }

  return result
}

let s = 'uxxdlselxmwyiguugtpsypfudffswvwyswyyiiyywsywvsffdufpysptguugiywmxlesldxxu'
let i = palindromeIndex(s)
console.log(i)
console.log(s.substring(0, i))
// console.log(palindromeIndex(string1))
// console.log(palindromeIndex(string2))
// console.log(palindromeIndex(string3))
// console.log(palindromeIndex(string4))
// console.log(palindromeIndex(string5))
// console.log(palindromeIndex(string6))
// console.log(palindromeIndex(string7))
// console.log(palindromeIndex(string8))

